### ISSUE TITLE
Some videos cannot be downloaded and throws an error when attempting to download

### ISSUE THREAD

**Issue by SteveJSzabo** [a-busman/DigitalFoundryUpdater#2]
**Describe the bug**
When the downloader is running, and it attempts to download some of the videos, we get Erno 22 errors

**To Reproduce**
When running and attempts to download certain videos, it throws an error immediately before moving onto the next video.

**Expected behavior**
The video downloads.

**Desktop:**
 - OS: Windows 10 Professional
 - Browser Chrome 88.0.4324.104
 - Version: Commit 10b7f67

**Additional context**
An example of the error being thrown:
2021-02-04 13:30:57 INFO     Downloading...
2/7 Destruction AllStars on PS5| 60FPS Arcade Action Analysis!
2021-02-04 13:30:57 ERROR    Failed to download Destruction AllStars on PS5| 60FPS Arcade Action Analysis!: [Errno 22] Invalid argument: 'E:/Plex/Other/DF/Destruction AllStars on PS5| 60FPS Arcade Action Analysis!.mp4'

**Comment by SteveJSzabo** [comment]
It didn't like the | character in the name. In downloader.py, I changed the .replace to use a - instead of the | and it's going happily along now.

**Comment by SteveJSzabo** [comment]
It also didn't like the ? character, so I added another replace for that as well

**Comment by a-busman** [comment]
That's fair. I didn't do much testing in Windows, and yeah the pipe isn't valid in Windows for file names. I'll do a real comprehensive, most compatible, file name sanitizing.

**Comment by a-busman** [comment]
Please try fc178a7476daabaf150c0162cac6dfafae6bce33

**Comment by SteveJSzabo** [comment]
This works!
